# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3c95170c1680f7efffa641fcb4a7980da13c054f3ac8b33d0a416438bad93562f9f5d995789c256752aa0604d45b4be21f0a99eed68a919b18828c422d12300

test:
  secret_key_base: d82e489a9091d5d360e9e079efc7270e5ee465fa6df8436e3ec747da1214aea9b4b578d0da982736d16536216cfabec0c495eb248aee88e302a71dcadf17a9d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
